#!/bin/sh
NEWPATH=$(dirname $(realpath $0))
OLDPATH=/Users/ruby1ruby1ruby1ruby1ruby1ruby1ruby1ruby1ruby1ruby1ruby1ruby1ruby1ruby1ruby1ruby1/.rbenv/versions/rubytemp

let COUNTDIFF=(${#OLDPATH}-${#NEWPATH})-1

HACKDIR=$(printf "%-${COUNTDIFF}s" ".")
HACKDIR=${HACK// /.}

ln -sf . "$HACKDIR"

find bin include lib share -type f | xargs perl -pi -e "s{$OLDPATH}{$NEWPATH/$HACKDIR}sg"
