#!/bin/sh
NEWPATH=$(dirname $(realpath $0))
OLDPATH=/Users/ruby1ruby1ruby1ruby1ruby1ruby1ruby1ruby1ruby1ruby1ruby1ruby1ruby1ruby1ruby1ruby1/.rbenv/versions/rubytemp

let COUNTDIFF=${#OLDPATH}-${#NEWPATH}
export COUNTDIFF

mimetypes=$(mktemp -t mimetypes.XXXXXX)
function cleanup {
    local rv=$?
    rm $mimetypes
    exit $rv
}
trap cleanup INT TERM EXIT

find $NEWPATH/{bin,include,lib,share} -type f | xargs file --mime > $mimetypes

grep binary $mimetypes | cut -d: -f1 | xargs perl -pi -e "undef \$/; 1 while s{$OLDPATH}{\"$NEWPATH\".\"/.\"x($COUNTDIFF/2).\"/\"x($COUNTDIFF%2)}sge"
grep text $mimetypes | cut -d: -f1| xargs perl -pi -e "undef \$/; 1 while s{$OLDPATH}{$NEWPATH}sg"
